---
- name: ping all servers
  hosts: all
  gather_facts: False
  connection: local
  tasks:
  - name: Connection-ping
    delegate_to: localhost
    command: ping -c 2 "{{ inventory_hostname }}"
    register: router_ping
